# Generated by Django 5.1.1 on 2024-10-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_folder", "0003_rename_cover_image_book_cover"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="available",
            new_name="is_available",
        ),
    ]
