# Generated by Django 5.2.5 on 2025-08-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_folder", "0005_alter_book_cover_featuredbooks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, max_length=255, upload_to="covers/"),
        ),
    ]
