# Generated by Django 5.1.1 on 2024-09-17 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('available', models.BooleanField(default=True)),
                ('isbn', models.CharField(max_length=255, unique=True)),
                ('cover_image', models.ImageField(upload_to='covers/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app_folder.category')),
            ],
        ),
    ]
