# Generated by Django 5.1.1 on 2024-10-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_folder", "0002_book_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="cover_image",
            new_name="cover",
        ),
    ]
